// Host test for comm/frame.h -- runs on the Mac, no embedded toolchain needed:
//
//   make -C spirant-daisy/v1/tests run
//
// The centrepiece is test_rust_generated_default_frame(): a real frame
// produced by the Pico's serializer, decoded here. That is the genuine
// cross-implementation check -- CRC, byte order, record layout, and the
// parameter table all have to agree for it to pass.

#include <assert.h>
#include <stdio.h>
#include <string.h>

#include "../comm/frame.h"

// --- The cross-language fixture ---------------------------------------------
// Default-state GetAll frame, generated by:
//
//   cd spirant-parameter-values-rs
//   cargo test wire::tests::default_getall_frame -- --nocapture
//
// That test prints this array in C syntax and asserts the same bytes on the
// Rust side, so the two copies cannot drift silently. If a PARAM_SPECS edit
// makes this test fail, regenerate the array from the command above rather
// than hand-editing it -- and update kParamTable in comm/param_table.h to
// match the new ranges.
static const uint8_t kDefaultGetAllFrame[97] = {
    0x13, 0x00, 0x00, 0x00, 0x00, 0x0F, 0x01, 0x00, 0x00, 0x00, 0x32, 0x04,
    0x00, 0x00, 0x00, 0x23, 0x05, 0x00, 0x00, 0x00, 0x42, 0x06, 0x00, 0x00,
    0x00, 0x96, 0x07, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00,
    0x09, 0x00, 0x00, 0x00, 0x28, 0x0C, 0x00, 0x00, 0x00, 0x32, 0x0D, 0x00,
    0x00, 0x00, 0x23, 0x0E, 0x00, 0x00, 0x00, 0x3C, 0x0F, 0x00, 0x00, 0x00,
    0x14, 0x10, 0x00, 0x00, 0x01, 0x99, 0x11, 0x00, 0x00, 0x00, 0x28, 0x12,
    0x00, 0x00, 0x00, 0x32, 0x13, 0x00, 0x00, 0x00, 0x50, 0x14, 0x00, 0x00,
    0x00, 0x4B, 0x15, 0x00, 0x00, 0x00, 0x55, 0x16, 0x00, 0x00, 0x1B, 0x58,
    0x35,
};

// The v0 patch defaults, in ascending global_idx order. Independently written
// out from the protocol section 6 table -- not read back out of the frame, or
// the test would only be checking the decoder against itself.
struct Expected
{
    uint8_t global_idx;
    int32_t value;
};

static const Expected kExpectedDefaults[19] = {
    {0, 15},    // Waveshape %
    {1, 50},    // Pulse Width %
    {4, 35},    // Resonance %
    {5, 66},    // Brightness %
    {6, 150},   // Cutoff Floor Hz
    {7, 0},     // Passband Gain %
    {8, 0},     // Drive %
    {9, 40},    // Output Trim %
    {12, 50},   // Chorus LFO Rate cHz
    {13, 35},   // Chorus LFO Depth %
    {14, 60},   // Chorus Delay %
    {15, 20},   // Chorus Feedback %
    {16, 409},  // Delay Time ms
    {17, 40},   // Delay Feedback %
    {18, 50},   // Delay Wet Mix %
    {19, 80},   // Delay Damping per-mille
    {20, 75},   // Reverb Send %
    {21, 85},   // Reverb Size %
    {22, 7000}, // Reverb Damp LP Hz
};

// --- Frame construction helpers ---------------------------------------------

// Build a well-formed frame from `records`, padding and appending the CRC the
// way the Pico's serializer does.
static void build_frame(uint8_t* frame, const Expected* records, uint8_t count)
{
    memset(frame, kPadByte, kFrameLen);
    frame[0] = count;
    for(uint8_t i = 0; i < count; i++)
    {
        uint8_t*      rec = frame + 1 + (size_t)i * kRecordLen;
        const int32_t v   = records[i].value;
        rec[0]            = records[i].global_idx;
        rec[1]            = (uint8_t)((uint32_t)v >> 24);
        rec[2]            = (uint8_t)((uint32_t)v >> 16);
        rec[3]            = (uint8_t)((uint32_t)v >> 8);
        rec[4]            = (uint8_t)((uint32_t)v);
    }
    frame[kCrcOffset] = crc8(frame, kCrcOffset);
}

// --- Tests ------------------------------------------------------------------

static void test_rust_generated_default_frame()
{
    Record       out[kMaxRecords];
    DecodeResult r = decode_frame(kDefaultGetAllFrame, out, kMaxRecords);

    assert(r.status == DecodeStatus::kOk);
    assert(r.count == 19);
    assert(r.skipped == 0);
    assert(r.clamped == 0);

    for(int i = 0; i < 19; i++)
    {
        assert(out[i].global_idx == kExpectedDefaults[i].global_idx);
        assert(out[i].value == kExpectedDefaults[i].value);
    }

    printf("  rust default GetAll frame ok (19 records)\n");
}

static void test_crc_mismatch_is_rejected()
{
    uint8_t frame[kFrameLen];
    memcpy(frame, kDefaultGetAllFrame, kFrameLen);
    frame[40] ^= 0x01;  // corrupt a value byte

    Record       out[kMaxRecords];
    DecodeResult r = decode_frame(frame, out, kMaxRecords);

    assert(r.status == DecodeStatus::kCrcMismatch);
    assert(r.count == 0);  // nothing partially applied

    printf("  crc mismatch rejected     ok\n");
}

static void test_unknown_command_ff_frame_is_rejected()
{
    // The Pico serves an 0xFF-filled frame for an unrecognised command byte
    // (protocol section 5.1). Count 0xFF is invalid and the CRC will not
    // verify; either rejection is correct, but it must never decode.
    uint8_t frame[kFrameLen];
    memset(frame, 0xFF, kFrameLen);

    Record       out[kMaxRecords];
    DecodeResult r = decode_frame(frame, out, kMaxRecords);

    assert(r.status != DecodeStatus::kOk);
    assert(r.count == 0);

    printf("  0xFF fill frame rejected  ok\n");
}

static void test_bad_count_is_rejected()
{
    uint8_t frame[kFrameLen];
    build_frame(frame, kExpectedDefaults, 19);
    frame[0]          = 20;  // one more than can exist
    frame[kCrcOffset] = crc8(frame, kCrcOffset);

    Record       out[kMaxRecords];
    DecodeResult r = decode_frame(frame, out, kMaxRecords);

    assert(r.status == DecodeStatus::kBadCount);
    assert(r.count == 0);

    printf("  count > 19 rejected       ok\n");
}

static void test_empty_getchanged_frame()
{
    uint8_t frame[kFrameLen];
    build_frame(frame, nullptr, 0);

    Record       out[kMaxRecords];
    DecodeResult r = decode_frame(frame, out, kMaxRecords);

    assert(r.status == DecodeStatus::kOk);
    assert(r.count == 0);

    printf("  empty GetChanged frame    ok\n");
}

static void test_padding_after_a_short_frame_is_ignored()
{
    const Expected records[2] = {{0, 42}, {22, 12000}};
    uint8_t        frame[kFrameLen];
    build_frame(frame, records, 2);

    Record       out[kMaxRecords];
    DecodeResult r = decode_frame(frame, out, kMaxRecords);

    assert(r.status == DecodeStatus::kOk);
    assert(r.count == 2);
    assert(out[0].global_idx == 0 && out[0].value == 42);
    assert(out[1].global_idx == 22 && out[1].value == 12000);

    printf("  short frame + padding     ok\n");
}

static void test_null_and_unknown_indices_are_skipped()
{
    // Index 2 is a null slot, 200 is out of range; index 0 is valid and must
    // still be applied.
    const Expected records[3] = {{0, 42}, {2, 1}, {200, 1}};
    uint8_t        frame[kFrameLen];
    build_frame(frame, records, 3);

    Record       out[kMaxRecords];
    DecodeResult r = decode_frame(frame, out, kMaxRecords);

    assert(r.status == DecodeStatus::kOk);
    assert(r.count == 1);
    assert(r.skipped == 2);
    assert(out[0].global_idx == 0 && out[0].value == 42);

    printf("  null/unknown idx skipped  ok\n");
}

static void test_out_of_range_values_are_clamped()
{
    // Waveshape is 0-100 %, Damp LP is 1000-18000 Hz.
    const Expected records[3] = {{0, 500}, {5, -20}, {22, 99999}};
    uint8_t        frame[kFrameLen];
    build_frame(frame, records, 3);

    Record       out[kMaxRecords];
    DecodeResult r = decode_frame(frame, out, kMaxRecords);

    assert(r.status == DecodeStatus::kOk);
    assert(r.count == 3);
    assert(r.clamped == 3);
    assert(out[0].value == 100);    // clamped to max
    assert(out[1].value == 0);      // clamped to min
    assert(out[2].value == 18000);  // clamped to max

    printf("  out-of-range clamped      ok\n");
}

static void test_negative_values_decode_as_signed()
{
    // No parameter currently has a negative range, but the wire format is
    // signed int32 and the decoder must not treat the sign bit as magnitude
    // before clamping.
    const Expected records[1] = {{0, -1}};
    uint8_t        frame[kFrameLen];
    build_frame(frame, records, 1);

    assert(frame[2] == 0xFF && frame[5] == 0xFF);  // two's complement on the wire

    Record       out[kMaxRecords];
    DecodeResult r = decode_frame(frame, out, kMaxRecords);

    assert(r.status == DecodeStatus::kOk);
    assert(r.count == 1);
    assert(r.clamped == 1);
    assert(out[0].value == 0);  // clamped up to Waveshape's min

    printf("  signed decode + clamp     ok\n");
}

static void test_table_matches_expected_defaults()
{
    // Guards the sync contract from the other direction: every index the
    // fixture carries must be an active slot, and its default must sit inside
    // the range this firmware believes in.
    for(int i = 0; i < 19; i++)
    {
        const ParamRange& range = kParamTable[kExpectedDefaults[i].global_idx];
        assert(range.active);
        assert(kExpectedDefaults[i].value >= range.min);
        assert(kExpectedDefaults[i].value <= range.max);
    }

    int active = 0;
    for(uint8_t i = 0; i < kNumSlots; i++)
        if(kParamTable[i].active)
            active++;
    assert(active == kNumActiveParams);

    printf("  param table consistency   ok\n");
}

int main()
{
    printf("frame_test\n");
    test_rust_generated_default_frame();
    test_crc_mismatch_is_rejected();
    test_unknown_command_ff_frame_is_rejected();
    test_bad_count_is_rejected();
    test_empty_getchanged_frame();
    test_padding_after_a_short_frame_is_ignored();
    test_null_and_unknown_indices_are_skipped();
    test_out_of_range_values_are_clamped();
    test_negative_values_decode_as_signed();
    test_table_matches_expected_defaults();
    printf("frame_test PASSED\n");
    return 0;
}
